# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enunciado', '0002_auto_20171121_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='abogado',
            new_name='materia',
        ),
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enunciado.Alumno'),
        ),
    ]
